### ISSUE TITLE
Zero downtime HAProxy

### ISSUE THREAD

**Issue by gpolaert** [Bahaika/whale-haproxy#1]
If you want a true zero downtine for the HAProxy service: http://engineeringblog.yelp.com/2015/04/true-zero-downtime-haproxy-reloads.html

**Comment by Bahaika** [comment]
This is a great idea, but to keep it simple I will try to implement a solution with a haproxy in front of another haproxy to have a smooth switching while reloading configuration. I'll let you know when it'll be fixed.

**Comment by Bahaika** [comment]
Implemented in commit [7367596](https://github.com/Bahaika/whale-haproxy/commit/73675966dac867738bf16d8817fbd710a703c607)
